version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: credo
    versions:
    - 1.5.4
